### ISSUE TITLE
ES Proposed Feature Checklist

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/polyfill#46]
[Sep 2014 TC39 notes](https://mail.mozilla.org/pipermail/es-discuss/2014-October/039827.html)
* [x] Math.denormz(x)
* [x] Math.fdenormz(x) = Math.denormz(Math.fround(x))
* [x] Math.imulh(a, b)
* [x] Math.umulh(a, b)
* [x] Math.iaddh(lo0, hi0, lo1, hi1)
* [x] Math.isubh(lo0, hi0, lo1, hi1)

**Comment by inexorabletash** [comment]
denormz/fdenormz are "stage 1" per the meeting notes, but not on the TC39 tracking doc.

The int64 helpers are "stage 0", but may be ditched in favor of http://littledan.github.io/int64.html
