### ISSUE TITLE
ES6 Final Tweaks

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/polyfill#48]
Per https://twitter.com/awbjs
- [x] ES6 WeakMap and WeakSet `clear` methods eliminated
- [x] ES6 final tweaks #2: `String.prototype.contains` renamed to `String.prototype.includes`
- [x] ES6 final tweaks #3: Symbols @@match, @@replace, @@search, @@split replace string names as double dispatch targets in `RegExp.prototype`
- [x] ES6 final tweak #4: added `RegExp.prototype.flags` for accessing flags string. Facilitates RegExp subclasses that add flags.
- ES6 final tweaks #5: `new RegExp(aRegExp, flags)` no longer throws. Instead clones first argument but with supplied flags.
  - _Can't usefully polyfill a constructor_
- ES6 final tweaks #6: at the top level of a module, the `this` binding evaluates to `undefined`.
  - _Can't polyfill modules_
- ES6 final tweaks #7: `Array.isArray(new Proxy([ ], { }))` returns true.
  - _Can't polyfill proxies_
- [ ] ES6 final tweaks #8: Smalltalk-like species pattern used in Array methods, etc. to determine constructor for derived objects. `let derived = new obj.constructor.species();`

**Comment by inexorabletash** [comment]
I did a pass to synchronize with the latest draft. The guts of `Promise` methods abstract operations need a bit more alignment, but overall I think it's in good shape.

I still have not tackled __@@species__ - pull requests (including tests!) welcome.
